### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by fabiointel** [NIVeriStandAdd-Ons/XNET-CAN-Bus-Monitor-Custom-Device#1]
Hello,
can you explain how can I use it in a Veristand Project?

I explain better my question. I have to monitor a can net. I want to have a list of frame and their values. I thought that your XNET-CAN-Bus-Monitor-Custom-Device is what I'm searching for... isn't true?

**Comment by AndreasStark** [comment]
Dear Fabio,

please call your local NI office for support for NI VeriStand or use the official forums (http://ni.com/support). Through github there is no guarantee for response time and accurate follow up. 

In your case I think you just need the standard XNET functionality built into NI VeriStand - please see the VeriStand help (http://zone.ni.com/reference/en-XX/help/372846J-01/TOC32.htm) or this: CAN, LIN, and FlexRay Interfaces for NI VeriStand - http://www.ni.com/white-paper/11540/en/

About this custom device  -from the readme: "The custom device currently only provides bus load and peak bus load" so if you're interested in these live parameters of the bus the CD is right for you.

**Comment by fabiointel** [comment]
thanks!!!
